name: Test

on:
  push:
  pull_request:

jobs:
  test-vimrc:
    uses: ./.github/workflows/test_vim_config.yaml
    with:
      vim_config_file: "./vimrc"

  test-gvimrc:
    uses: ./.github/workflows/test_vim_config.yaml
    with:
      vim_config_file: "./gvimrc"

  test-polish-spell:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./polish_spell"
      result_file: "./spell/pl.utf-8.spl"

  test-retrobox-scheme:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./retrobox_scheme"
      result_file: "./colors/retrobox.vim"

  test-shell-indent:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./shell_indent"
      result_file: "./indent/sh.vim"

  test-smart-tabs:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./smart_tabs"
      result_file: "./plugin/smart_tabs.vim"
