name: Test

on:
  push:
  pull_request:

jobs:
  test-vimrc:
    uses: mikobartnicki/actions/.github/workflows/command_test.yaml@main
    with:
      command_to_test: vim -u ./vimrc -e -c 'q'

  test-gvimrc:
    uses: mikobartnicki/actions/.github/workflows/command_test.yaml@main
    with:
      command_to_test: vim -u ./gvimrc -e -c 'q'

  test-polish-spell:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./polish_spell"
      result_file: "./spell/pl.utf-8.spl"

  test-retrobox-scheme:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./retrobox_scheme"
      result_file: "./colors/retrobox.vim"

  test-shell-indent:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./shell_indent"
      result_file: "./indent/sh.vim"

  test-smart-tabs:
    uses: ./.github/workflows/test_bash_script.yaml
    with:
      script_name: "./smart_tabs"
      result_file: "./plugin/smart_tabs.vim"
