name: Test Bash script

on:
  workflow_call:
    inputs:
      script_name:
        required: true
        type: string
      result_file:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing previous result file (if any)
        run: rm -f "${{ inputs.result_file }}"

      - name: Make script executable
        run: chmod +x "${{ inputs.script_name }}"

      - name: Execute script
        run: |
          "${{ inputs.script_name }}"
          echo "Exited with code: $?"

      - name: Check the result
        run: |
          if [ -f "${{ inputs.result_file }}" ]; then
            echo "${{ inputs.result_file }} created succesfully."
          else
            "${{ inputs.result_file }} was not created!" >&2
            exit 1
          fi
