# Tests the correctness of Vim/gVim configuration files and the execution of
# optional shell scripts.
#
# Latest revision: 2025-03-06
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Test

on:
  push:
  pull_request:

jobs:
  test-vimrc:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: vim -u ./vimrc -e -c 'q'

  test-gvimrc:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: vim -u ./gvimrc -e -c 'q'

  test-polish-spell:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: ./polish_spell
      is_script: true
      expected_file: ./spell/pl.utf-8.spl

  test-retrobox-scheme:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: ./retrobox_scheme
      is_script: true
      expected_file: ./colors/retrobox.vim

  test-shell-indent:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: ./shell_indent
      is_script: true
      expected_file: ./indent/sh.vim

  test-smart-tabs:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: ./smart_tabs
      is_script: true
      expected_file: ./plugin/smart_tabs.vim
