name: Test Vim configuration file

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test vimrc
        run: vim -u ./vimrc -e -c 'quit'
