name: Test Vim config

on:
  workflow_call:
    inputs:
      vim_config_file:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test ${{ inputs.vim_config_file }} file
        run: vim -u "${{ inputs.vim_config_file }}" -e -c 'q'
