name: Test

on:
  push:
  pull_request:

jobs:
  test-vimrc:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: vim -u ./vimrc -e -c 'q'

  test-gvimrc:
    uses: mikobartnicki/actions/.github/workflows/test_shell_command.yaml@main
    with:
      command_to_test: vim -u ./gvimrc -e -c 'q'

  test-polish-spell:
    uses: mikobartnicki/actions/.github/workflows/test_shell_script.yaml@main
    with:
      script_to_test: "./polish_spell"
      expected_file: "./spell/pl.utf-8.spl"

  test-retrobox-scheme:
    uses: mikobartnicki/actions/.github/workflows/test_shell_script.yaml@main
    with:
      script_to_test: "./retrobox_scheme"
      expected_file: "./colors/retrobox.vim"

  test-shell-indent:
    uses: mikobartnicki/actions/.github/workflows/test_shell_script.yaml@main
    with:
      script_to_test: "./shell_indent"
      expected_file: "./indent/sh.vim"

  test-smart-tabs:
    uses: mikobartnicki/actions/.github/workflows/test_shell_script.yaml@main
    with:
      script_to_test: "./smart_tabs"
      expected_file: "./plugin/smart_tabs.vim"
